#!/bin/bash

# Script ini untuk mengalih-tuliskan Kamus Besar Bahasa Indonesia edisi IV
# tahun 2008 dari bentuk PDF ke bentuk teks biasa (plain text)
#
# Membutuhkan paket pdftotext, awk, dan bash (minimal versi 4)
#
# Teks yang dihasilkan script ini masih harus disunting secara manual


readonly KBBI='sumber/Kamus-Besar-Bahasa-Indonesia.pdf'
readonly LEMA='sumber/Lema_Tertinggal_KBBI_Ed._Keempat_Rev_Ver_4.pdf'
readonly DEPS='pdftotext awk bash'

# FUNCTIONS --------------------------------------------------------------------

usage() {
  printf '%s\n' "
 Cara pakai: ${0##*/} PILIHAN

 Mengalih-tuliskan berkas PDF Kamus Besar Bahasa Indonesia edisi IV (2008)
 ke dalam bentuk berkas teks biasa.

 Menjalankan ${0##*/} tanpa PILIHAN sama dengan menjalankan -g, -t, dan -u secara berurutan.

 PILIHAN:
   -g --gabung       Gabungkan berkas teks berdasar huruf lema
   -t --teks         Ubah berkas PDF KBBI menjadi teks
   -u --ubah         Perbaiki karakter hasil OCR yang salah
   -h --help         Tampilkan bantuan ini
 "
}

# tampilkan pesan berupa huruf tebal berwarna hijau
hijau() {
  printf "\e[1;32m$1\n\e[0;39;49m"
}

# tampilkan pesan berupa huruf tebal berwarna coklat
coklat() {
  printf "\e[1;33m$1\n\e[0;39;49m"
}

# tampilkan pesan berupa huruf tebal berwarna merah
merah() {
  printf "\e[1;31m$1\n\e[0;39;49m"
}

# periksa ketersediaan aplikasi yang dibutuhkan, jika tidak ada, hentikan skrip
check_deps() {
  printf "\n ${0##*/} sekarang akan memeriksa ketersediaan program yang ia butuhkan untuk bekerja.\n"

  for i in $DEPS; do
    if [[ -x $(which $i 2>/dev/null) ]]
    then
      hijau " - $i: OK"
    else
      merah " - $i: Tidak ada!"
      coklat " Harap terlebih dahulu memasang paket yang menyediakan $i."
      exit 1
    fi
  done
}

# ubah pdf menjadi berkas biasa menggunakan pdftotext
pdf_to_text() {
  [[ ! -d 'teks' ]] && mkdir 'teks'

  local i

  for i in {19..129}; do
    hijau " Mengubah laman ${i} menjadi $0/teks/kbbi4-$i.txt"
    # laman untuk lema a memiliki tinggi bagian nomor yang berbeda dengan
    # halaman lainnya (sekitar 600px pada resolusi 500dpi)
    pdftotext -f "$i" -l "$i" -r 500 -eol unix -nopgbrk -x 0 -y 600 -W 3250 -H 3636 "$KBBI" teks/kbbi4-"$i".txt
  done

  for i in {130..1490}; do
    hijau " Mengubah laman ${i} menjadi $0/teks/kbbi4-$i.txt"
    pdftotext -f "$i" -l "$i" -r 500 -eol unix -nopgbrk -x 0 -y 436 -W 3250 -H 3800 "$KBBI" teks/kbbi4-"$i".txt
  done

  # Lema_Tertinggal_KBBI_Ed._Keempat_Rev_Ver_4 hanya akan diubah ke teks
  # untuk selanjutnya disunting secara manual
  hijau " Mengubah ${LEMA##*/} menjadi $0/teks/${LEMA##*/}.txt"
  pdftotext -r 500 -eol unix -nopgbrk "$LEMA" teks/"${LEMA##*/}".txt
}

# kelompokkan kata berdasar huruf awal
group_text() {
  cat teks/kbbi4-{19..129}.txt > teks/kbbi4-A.txt
  cat teks/kbbi4-{130..263}.txt > teks/kbbi4-B.txt
  cat teks/kbbi4-{264..319}.txt > teks/kbbi4-C.txt
  cat teks/kbbi4-{320..390}.txt > teks/kbbi4-D.txt
  cat teks/kbbi4-{391..418}.txt > teks/kbbi4-E.txt
  cat teks/kbbi4-{419..439}.txt > teks/kbbi4-F.txt
  cat teks/kbbi4-{440..516}.txt > teks/kbbi4-G.txt
  cat teks/kbbi4-{517..553}.txt > teks/kbbi4-H.txt
  cat teks/kbbi4-{554..585}.txt > teks/kbbi4-I.txt
  # tidak ada lema J di berkas PDF KBBI 2008
  #cat teks/kbbi4-{..}.txt > teks/kbbi4-J.txt
  cat teks/kbbi4-{586..764}.txt > teks/kbbi4-K.txt
  cat teks/kbbi4-{765..866}.txt > teks/kbbi4-L.txt
  cat teks/kbbi4-{867..968}.txt > teks/kbbi4-M.txt
  cat teks/kbbi4-{969..989}.txt > teks/kbbi4-N.txt
  cat teks/kbbi4-{990..1002}.txt > teks/kbbi4-O.txt
  # tidak ada lema P di berkas PDF KBBI 2008
  #cat teks/kbbi4-{..}.txt > teks/kbbi4-P.txt
  cat teks/kbbi4-1003.txt > teks/kbbi4-Q.txt
  cat teks/kbbi4-{1004..1092}.txt > teks/kbbi4-R.txt
  cat teks/kbbi4-{1093..1259}.txt > teks/kbbi4-S.txt
  cat teks/kbbi4-{1260..1430}.txt > teks/kbbi4-T.txt
  cat teks/kbbi4-{1431..1459}.txt > teks/kbbi4-U.txt
  cat teks/kbbi4-{1460..1467}.txt > teks/kbbi4-V.txt
  cat teks/kbbi4-{1468..1481}.txt > teks/kbbi4-W.txt
  cat teks/kbbi4-1482.txt > teks/kbbi4-X.txt
  cat teks/kbbi4-{1483..1485}.txt > teks/kbbi4-Y.txt
  cat teks/kbbi4-{1486..1490}.txt > teks/kbbi4-Z.txt
}

# perbaiki kata hasil konversi pdftotext
perbaiki_kata() {
  local i
  for i in {A..Z}; do
    if [ -f "teks/kbbi4-$i.txt" ]; then
      coklat " Memperbaiki kata di berkas $i"

      # kbbi 2008 menggunakan drop cap letter pada halaman awal lema
      # perintah berikut akan menghapus huruf yang berada di baris 1 tersebut
      awk -i inplace 'NR>1' "teks/kbbi4-$i.txt"

      # hapus baris kosong
      awk -i inplace 'NF' "teks/kbbi4-$i.txt"

      # pdftotext gagal menerjemahkan beberapa karakter
      # ubah dash (yang aslinya berupa double dash) menjadi double dash
      awk -i inplace '/ -[[:alnum:]]/{gsub(" -", " -- ")};1' "teks/kbbi4-$i.txt"
      # ubah tanda kutip
      awk -i inplace '{gsub("[“”]", "\"")};1' "teks/kbbi4-$i.txt"
      # ubah ĺ menjadi ->
      awk -i inplace '{gsub("ĺ", "->")};1' "teks/kbbi4-$i.txt"
      # ubah o menjadi -> pada baris di bawah 5 kolom
      awk -i inplace 'NF<5 {gsub(" o ", "->")};1' "teks/kbbi4-$i.txt"

      # kbbi 2008 menggunakan angka di depan lema yang memiliki banyak arti
      # angka tersebut dirasa tidak penting dan akan dihapus oleh perintah berikut
      awk -i inplace '!/^[[:digit:]]$/' "teks/kbbi4-$i.txt"

      # gabung baris berdasar lema
      awk -v huruf=^"[$i${i,,}]" '$0 ~ huruf {if (x)print x;x="";}{x=(!x)?$0:x" "$0;}END{print x;}' "teks/kbbi4-$i.txt" > "teks/$i.txt"
    fi
  done
}

# MAIN -------------------------------------------------------------------------

case $1 in
  -g|--gambar)
    check_deps
    group_text
  ;;
  -t|--teks)
    check_deps
    pdf_to_text
  ;;
  -u|--ubah)
    check_deps
    perbaiki_kata
  ;;
  -h|--help)
    usage
    exit 0
  ;;
  *)
    check_deps
    pdf_to_text
    group_text
    perbaiki_kata
    merah " Menghapus semua berkas $0/teks/kbbi4-*.txt"
    rm teks/kbbi4-*.txt
  ;;
esac
