#!/bin/bash

split_pdf_to_jpegs() {
  for i in {1485..1489}; do
    convert -density 1200 Kamus-Besar-Bahasa-Indonesia.pdf[$i] /tmp/Z-$i.jpg
  done
}

convert_to_text() {
  find /tmp -maxdepth 1 -type f -iname "Z-*" | xargs -I '{}' tesseract -l ind '{}' '{}'
}

move_text_to_letter_folder() {
  mv /tmp/*.txt text/Z/
}

remove_jpegs() {
  rm /tmp/*.jpg
}

while read berkas; do
  # cetak baris berisi dan ganti newline ganda untuk baris yang kosong
  awk -i inplace '$0 != "" {printf "%s ",$0} $0 == "" {printf "\n"}' "$berkas"
  
  # ganti tanda sambung tunggal (single dash)
  awk -i inplace '{print gensub(/(^|[^-])- /, "\\1\\2", "g");}' "$berkas"
  
  # beberapa karakter kacau karena OCR yang tidak sempurna, sed berikut adalah
  # upaya memulihkannya
  sed -i 's|”|"|g;s|a\x27|d|g;s|»|~|g;s| F is | Fis |g;s| 71 | n |g;s|— ||g' "$berkas"

  # delete trailing whitespace (spaces, tabs) from end of each line
  awk '{sub(/[ \t]+$/, "")};1'

  #sed -e '/ \x27 /,+1d' "$berkas"

  for lc in {a..z} ; do UC=${lc^}; awk -i inplace '$1 ~ /^["'"$lc$UC"'"]/ {print} $1 ~ !/^["'"$lc$UC"'"]/ {printf "%s ", $0}' ${UC}.txt ; done
done < <(find text/ -type f -iname "*.txt")

while read map; do
  cat $map >> ${map%\/*}.txt
done < <(find text -type f | sort -t '-' -k 2n)
